---
- name: Instala o apache
  hosts: web
  become: yes

  tasks:
   - name: instala o pacote
     yum:
       name: httpd
       state: present

   - name: inicia o serviço
     service:
       name: httpd
       state: started
